### ISSUE TITLE
Disable picker per field

### ISSUE THREAD

**Issue by tobimori** [junohamburg/kirby-visual-block-selector#1]
I use the Blocks field for several things:
- Sometimes as a page builder, where this plugin nails it!
- Sometimes for defining structure-like data, where I don't have a frontend representation, no preview image to use and icons would totally be enough for that.

For the second purpose, it'd be cool to be able to toggle the preview via a Field prop.

**Comment by SebastianEberlein-JUNO** [comment]
Thanks for your feedback!

Unfortunately, adding a custom field property like `layout: cards` is not passed from the blueprint to the Vue component. The Kirby pages API seems to ignore any custom property.

But we just released an update that might help you: If no preview images exist for the corresponding `blocks` field, the default Kirby block selector is displayed.

**Comment by tobimori** [comment]
Awesome, thanks for the update! This also solves my issue, so I'll close this.
