### ISSUE TITLE
v4 compatibility

### ISSUE THREAD

**Issue by distantnative** [junohamburg/kirby-visual-block-selector#2]
Hi there,

Just wanted to give a heads up on a small change that this plugin will need to support Kirby 4 (currently in development):

- https://github.com/junohamburg/kirby-visual-block-selector/blob/main/index.js#L14
In v4, `user` won't ever be null but always a state object. So it needs to check for `user.id === null`. Ideally even:

```js
if (window.panel.user.id === null) return;
```

For v4 we will likely keep the Vuex store around (even though not using it ourselves anymore), but it could be that for v5 (in summer 2024) we would drop it from the core. Then we would need to think about a better alternative for you.

**Comment by SebastianEberlein-JUNO** [comment]
Thanks for the heads up, I added a fix in the latest release.

**Comment by tobimori** [comment]
Works again, thank you very much :)
