### ISSUE TITLE
Refactor for Kirby v4 and future versions

### ISSUE THREAD

**Issue by SebastianEberlein-JUNO** [junohamburg/kirby-visual-block-selector#3]
- [x] Update to new Kirby UI
- [ ] ~~Replace media query with container query?~~
- [ ] Replace Vuex store with new Panel JavaScript API?
- [ ]  Add option to specify preview images directory?

**Comment by tobimori** [comment]
@SebastianEberlein-JUNO - just fyi, the new alpha.5 breaks the plugin. probably because the block selector got a new component.

**Comment by SebastianEberlein-JUNO** [comment]
Thanks for the info! There are a lot of changes in the BlockSelector Vue component and in the overall UI. 

We are planning to release a separate v4 version of this plugin – probably ~~end of July, early August~~ | ~~in August~~ | when the first Kirby 4 beta is available and/or the Kirby 4 docs are more detailed.

**Comment by SebastianEberlein-JUNO** [comment]
There’s now a [v4-beta](https://github.com/junohamburg/kirby-visual-block-selector/tree/v4-beta) branch with an updated design.

**Comment by tobimori** [comment]
Works great, thanks for the update!
