### ISSUE TITLE
Compatibility with Kirby 4.1

### ISSUE THREAD

**Issue by MathiasGmeiner** [junohamburg/kirby-visual-block-selector#4]
With Kirby 4.1 the k-overlay dialog is empty. Everything is fine with 4.0.3.
So far I get no error message.

![CleanShot 2024-01-31 at 11 43 44@2x](https://github.com/junohamburg/kirby-visual-block-selector/assets/103595/827aa8fc-3f63-415d-a025-27a2321b9704)

**Comment by SebastianEberlein-JUNO** [comment]
I just released a new version that should be compatible with Kirby 4.0 and 4.1. Can you please check if it works in your kirby installation?

**Comment by MathiasGmeiner** [comment]
@SebastianEberlein-JUNO thanks a lot, the new version works fine!
